on: 
  release:
    types:
      - created

name: luci-app-xclient
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
      REPF: ${{ github.repository }}
      PKGN: ${{ 'luci-app-xclient' }}

    steps:
    - name: Checkout - ${{ github.ref }}
      uses: actions/checkout@master

    - name: Prepare SDK ENV
      run: |
        wget -q "${URL}"
        tar xJf openwrt-sdk-*.tar.xz -C ../
        mv -f "${GITHUB_WORKSPACE}" ../src
        mv ../openwrt-sdk-* "${GITHUB_WORKSPACE}"

    - name: Install dependencies
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: TAG
      run: |
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
          
    - name: Prepare targets
      run: |
        REP=$(basename "${REPF}")
        mv -vf ../src "package/${REP}"


    - name: Load custom configuration
      env:
        DEBIAN_FRONTEND: noninteractive
        CONFIG_FILE: '.config'
      run: |
        REP=$(basename "${REPF}")
        [ -e "package/${REP}/${CONFIG_FILE}" ] && mv "${CONFIG}" .config
        make defconfig

    - name: Build target
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        make package/${PKGN}/compile -j$(nproc) V=s
        mkdir ../bin
        find bin/ -type f -name "*${PKGN}*" | xargs -t -i mv -vf {} ../bin

    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('{0}.{1}.{2}', github.workflow, github.actor, github.event_name) }}
        path: ../bin
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          draft: true
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: ../bin/*.ipk
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
